### ISSUE TITLE
Missing virtio probably due to an outdated kernel config

### ISSUE THREAD

**Issue by derkuci** [alexhaydock/zfs-on-wsl#2]
Hi,

Thank you so much for providing a precompiled kernel with ZFS support!  This benefits people like me who is too lazy to do the kernel build :-)

I used your kernel (bzImage) on Windows 11, and it works!  I didn't use the other two tgz files (and I didn't do the make install).  Instead I used the user space packages from [OpenZFS](https://openzfs.github.io/openzfs-docs/Getting%20Started/).  Their version is zfs 2.0.6 but it works OK with your kernel (with zfs 2.1.0).

One issue, though, is that virtio is missing and I no longer am able to access /mnt/c.  There is a similar issue [reported here](https://github.com/microsoft/WSL/issues/7223).  The suggestion is to use the config from the linux-msft-wsl-5.10.y branch (instead of the master branch).

Hope you may find this helpful and provide an updated kernel :-)

Thanks again.

**Comment by alexhaydock** [comment]
Thanks! I'm glad you managed to get it running.

I did wonder whether the userspace components from older ZFS versions would work. I figured they might, but didn't test it. Glad it worked for you. 

I think it's a sensible suggestion to update the config the way you suggest so I'll work on that soon. Sadly I don't have a Windows 11 capable machine to test on, so I'm a bit limited.

**Comment by alexhaydock** [comment]
I'd quite like to update this to package the userspace utilities as a .deb package too, to make the process of using them a lot less messy.

**Comment by derkuci** [comment]
Thanks!  I should have mentioned that my laptop doesn't meet the cpu requirement for Windows 11 but I anyway upgraded it to Windows 11 when it was allowed with the windows insider program.  I don't particularly like Windows 11 against 10, but its WSLg is certainly much nicer.  I can test and report back when you make a new kernel.

The OpenZFS website provides deb packages.  I use CentOS so I don't know if the deb packages work with your kernel or not.  But maybe someone can take a try?

**Comment by alexhaydock** [comment]
I think this should no longer be an issue, as my latest updates rework the script to use the kernel code from Microsoft's WSL kernel Git repo rather than direct from kernel.org
