### ISSUE TITLE
build_wsl_kernel.sh looking for v6.x kernels in v5.x directory

### ISSUE THREAD

**Issue by mcladams** [alexhaydock/zfs-on-wsl#5]
Error is in line 49.
`wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${KERNELVER}.tar.xz -O /tmp/kbuild/kernel.tar.xz`

Currently running:
`mike@A515:~/git/zfs-on-wsl$ sudo ./build_wsl_kernel.sh
+ [[ 0 -ne 0 ]]
+ source ./vars.sh
++ export KERNELVER=6.4.12
++ KERNELVER=6.4.12
++ export ZFSVER=2.1.12
++ ZFSVER=2.1.12
++ export KERNELNAME=ubuntu-preview
++ KERNELNAME=ubuntu-preview
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu mantic InRelease
Hit:2 http://security.ubuntu.com/ubuntu mantic-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu mantic-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu mantic-backports InRelease
Reading package lists... Done
...`

I'll note any other issues after I've built, installed & tested & maybe hit (tweet) you on ultra (the fediverse/masstadon) with other notes.

Up to date ubuntu 23.10 on wsl2 latest microsoft kernel on win 11 insider preview dev channel
`root@A515:~# uname -a
Linux A515 5.15.90.4-microsoft-standard-WSL2 #1 SMP Tue Jul 18 21:28:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

`PS C:\Users\Mike> uname -a
Windows_NT A515 10.0 23526 x86_64 MS/Windows (Windows 11)`

**Comment by alexhaydock** [comment]
Thanks for testing this. I should get around to updating this but sadly I don't have any Windows machines for testing that are conveniently available. 

I did have grand plans of building this into a Debian package so it actually builds a proper installable package to use, but never quite got around to that.

**Comment by mclad** [comment]
I'll fork and clone it if there are any more things I find. Its a super useful script (last two times I read the script but did it all manually), if its only bugfixes I can help with that.

(I had grand plans for a script to convert ubuntu zsys bpool/rpool system to zfsbootmenu zroot only system... not happening... but I did just manually converted two distros with default btrfs root with grub-btrfs/snapper/timeshift to zfsbootmenu/sanoid... that would be a useful thing.)

**Comment by mclad** [comment]
Apparently successful, will test in next days

`Kernel: arch/x86/boot/bzImage is ready  (#1)
+ make modules_install
  DEPMOD  /lib/modules/6.4.12-${KERNELNAME}
+ mkdir -p /mnt/c/ZFSonWSL
+ cp -fv /usr/src/linux-6.4.12-ubuntu-preview/arch/x86/boot/bzImage /mnt/c/ZFSonWSL/bzImage-new
'/usr/src/linux-6.4.12-ubuntu-preview/arch/x86/boot/bzImage' -> '/mnt/c/ZFSonWSL/bzImage-new'
+ cd /tmp/kbuild
+ tar -czf linux-6.4.12-ubuntu-preview.tgz /usr/src/linux-6.4.12-ubuntu-preview
+ tar -czf zfs-2.1.12-for-6.4.12-ubuntu-preview.tgz /usr/src/zfs-2.1.12-for-linux-6.4.12-ubuntu-preview`

**Comment by alexhaydock** [comment]
I think this should no longer be an issue, as my latest updates rework the script to use the kernel code from Microsoft's WSL kernel Git repo rather than direct from kernel.org
